### ISSUE TITLE
Login to the Hub using Rainbown (Metamask and others)

### ISSUE THREAD

**Issue by rodrigooler** [Kindelia/Sites#12]
As suggested by @steinerkelvin , the login will be done through the wallet and we will use Rainbow to connect the end user wallet and capture some data like wallet address and the image as well

![Image](https://user-images.githubusercontent.com/5496931/187061527-0b42315f-5a1c-4a85-b4c7-0c0d5c475f45.png)

https://www.rainbowkit.com/

# Tasks

- [x] [Installation](https://www.rainbowkit.com/docs/installation)
- [x] [Configure](https://www.rainbowkit.com/docs/installation#configure)
- [x] [Set Provider](https://www.rainbowkit.com/docs/installation#wrap-providers)
- [x] [Add ConnectButton](https://www.rainbowkit.com/docs/connect-button)

**Comment by rodrigooler** [comment]
A brief detail of how it's going

![Image](https://user-images.githubusercontent.com/5496931/187061930-3bb4bcb9-b477-4af3-9be9-c63a9b1d9e3a.png)
