### ISSUE TITLE
Develop Hub main page

### ISSUE THREAD

**Issue by rodrigooler** [Kindelia/Sites#9]
Development of the main page of the hub containing the following aspects drawn in figma

![Image](https://user-images.githubusercontent.com/5496931/186772076-6d19fb4f-d4b1-4994-bc41-16cd0192511d.png)

# Tasks

- [x] Create Navbar 
- [x] Add Kindelia logo
- [x] Add Footer
- [x] Search component below the logo
- [x] Create data mock for **featured** and **discover**
- [x] Develop **Featured** section
- [x] Develop **Discover** section

# Others
- [x] Create hook useBlockQuery
- [x] Create hook useBlocksQuery
- [x] Initial configuration of react-query
- [x] Change from ramda to @fxts/core
- [x] Icon provider code refactoring
